# Feature toggles and flags
features:
  platinum:
    enabled: true
    custom_parlay_image: true
    custom_win_emoji: true
    custom_loss_emoji: true
    advanced_analytics: true
  beta:
    new_dashboard: false
    experimental_api: false
  general:
    reaction_monitor: true
    leaderboard: true
    parlay_betting: true
