# Command and permission settings
permissions:
  commands:
    setup:
      enabled: true
      roles:
        - admin
    reaction_monitor:
      enabled: true
      roles:
        - admin
        - moderator
    leaderboard:
      enabled: true
      roles:
        - everyone
    premium:
      enabled: true
      roles:
        - admin
        - premium
  guild_overrides:
    1328116926903353398:
      commands:
        reaction_monitor:
          enabled: false
        leaderboard:
          enabled: true
