# Sport categories and their leagues
SPORT_CATEGORIES:
  OTHER:
    - MANUAL
  BASKETBALL:
    - NBA
    - NCAAB
    - WNBA
    - EUROLEAGUE
    - CBA
    - BRITISH BASKETBALL LEAGUE
    - G_LEAGUE
    - NBL
    - BASKETBALL_CHAMPIONS_LEAGUE
    - FIBA_AMERICAS
    - FIBA_ASIA
    - FIBA_EUROPE
    - FIBA_OCEANIA
    - FIBA_AFRICA
  FOOTBALL:
    - NFL
    - NCAAF
    - CFL
    - XFL
    - USFL
    - AFL
    - ARENA_FOOTBALL
    - IFAF
    - WORLD_FOOTBALL_LEAGUE
  HOCKEY:
    - NHL
    - AHL
    - NCAAH
    - KHL
    - SHL
    - DEL
    - LIIGA
    - NLA
    - EIHL
    - CHL
    - SPHL
    - ECHL
    - IIHF_WORLD_CHAMPIONSHIP
    - IIHF_WORLD_JUNIORS
    - OLYMPIC_HOCKEY
  BASEBALL:
    - MLB
    - NPB
    - KBO
    - NCAAB_BASEBALL
    - LIDOM
    - ABL
    - CPBL
    - LMB
    - WBSC_PREMIER12
    - WORLD_BASEBALL_CLASSIC
    - CARIBBEAN_SERIES
  SOCCER:
    - MLS
    - EPL
    - LA_LIGA
    - BUNDESLIGA
    - SERIE_A
    - LIGUE_1
    - BRAZIL_SERIE_A
    - UEFACL
    - UEFA CHAMPIONS LEAGUE
    - ChampionsLeague
    - UEFA EUROPA LEAGUE
    - EuropaLeague
    - WORLDCUP
    - Allsvenskan
    - Superettan
    - Damallsvenskan
    - Elitettan
    - Svenska_Cupen
    - Svenska_Cupen_-_Women
    - Ettan_-_Norra
    - Ettan_-_Södra
    - Ettan_-_Relegation_Round
    - Division_2_-_Norra_Götaland
    - Division_2_-_Norra_Svealand
    - Division_2_-_Norrland
    - Division_2_-_Södra_Svealand
    - Division_2_-_Västra_Götaland
    - Division_2_-_Östra_Götaland
  TENNIS:
    - ATP
    - WTA
    - ITF
    - GRAND_SLAM
    - DAVIS_CUP
    - BILLIE_JEAN_KING_CUP
    - ATP_FINALS
    - WTA_FINALS
    - OLYMPIC_TENNIS
  GOLF:
    - PGA
    - LPGA
    - EUROPEAN_TOUR
    - KORN_FERRY
    - CHAMPIONS_TOUR
    - LIV_GOLF
    - RYDER_CUP
    - PRESIDENTS_CUP
    - SOLHEIM_CUP
    - OLYMPIC_GOLF
  RACING:
    - F1
    - NASCAR
    - INDYCAR
    - MOTOGP
    - WRC
    - WEC
    - IMSA
    - SUPER_GT
    - DTM
    - BTCC
    - FORMULA_E
    - WORLD_RALLYCROSS
    - WORLD_TOURING_CARS
  FIGHTING:
    - UFC
    - MMA
    - BOXING
    - BELLATOR
    - ONE_CHAMPIONSHIP
    - PFL
    - RIZIN
    - K_1
    - GLORY
    - BELLATOR_KICKBOXING
    - ONE_KICKBOXING
  ESPORTS:
    - LOL
    - CSGO
    - DOTA2
    - VALORANT
    - OVERWATCH
    - RAINBOW_SIX
    - ROCKET_LEAGUE
    - FIFA
    - STARCRAFT
    - HEARTHSTONE
    - STREET_FIGHTER
    - TEKKEN
    - SMASH
    - APEX_LEGENDS
  CRICKET:
    - IPL
    - BBL
    - PSL
    - CPL
    - THE_HUNDRED
    - T20_BLAST
    - TEST_CRICKET
    - ODI
    - T20I
    - WORLD_CUP
    - CHAMPIONS_TROPHY
  RUGBY:
    - SUPER_RUGBY
    - SIX_NATIONS
    - RUGBY_CHAMPIONSHIP
    - PRO14
    - TOP14
    - PREMIERSHIP
    - WORLD_CUP
    - SEVENS
    - OLYMPIC_RUGBY
  AUSTRALIAN_FOOTBALL:
    - AFL
    - AFLW
    - VFL
    - SANFL
    - WAFL
    - NEAFL
  VOLLEYBALL:
    - FIVB
    - CEV
    - AVC
    - NORCECA
    - WORLD_LEAGUE
    - NATIONS_LEAGUE
    - WORLD_CUP
    - OLYMPIC_VOLLEYBALL
  HANDBALL:
    - EHF_CL
    - EHF_CUP
    - WORLD_CHAMPIONSHIP
    - EUROPEAN_CHAMPIONSHIP
    - OLYMPIC_HANDBALL
  LACROSSE:
    - NLL
    - PLL
    - MLL
    - WORLD_LACROSSE_CHAMPIONSHIP
  FIELD_HOCKEY:
    - FIH_PRO_LEAGUE
    - WORLD_CUP
    - OLYMPIC_FIELD_HOCKEY
    - EUROPEAN_CHAMPIONSHIP
    - PAN_AMERICAN_CUP
  BADMINTON:
    - BWF
    - THOMAS_CUP
    - UBER_CUP
    - SUDIRMAN_CUP
    - WORLD_CHAMPIONSHIPS
    - OLYMPIC_BADMINTON
  TABLE_TENNIS:
    - ITTF
    - WORLD_CHAMPIONSHIPS
    - WORLD_CUP
    - OLYMPIC_TABLE_TENNIS
  SNOOKER:
    - WORLD_CHAMPIONSHIP
    - UK_CHAMPIONSHIP
    - MASTERS
    - CHAMPION_OF_CHAMPIONS
    - TOUR_CHAMPIONSHIP
  DARTS:
    - DARTS
    - PDC
    - BDO
    - WORLD_CHAMPIONSHIP
    - PREMIER_LEAGUE
    - WORLD_MATCHPLAY
    - WORLD_GRAND_PRIX
  CYCLING:
    - TOUR_DE_FRANCE
    - GIRO_D_ITALIA
    - VUELTA_A_ESPANA
    - WORLD_CHAMPIONSHIPS
    - OLYMPIC_CYCLING
