"""NHL (Ice Hockey) team name mappings."""

# NHL Teams (Ice Hockey)
NHL_TEAM_MAPPINGS = {
    "Oilers": "edmonton_oilers",
    "Edmonton Oilers": "edmonton_oilers",
    "Flames": "calgary_flames",
    "Calgary Flames": "calgary_flames",
    "Canucks": "vancouver_canucks",
    "Vancouver Canucks": "vancouver_canucks",
    "Maple Leafs": "toronto_maple_leafs",
    "Toronto Maple Leafs": "toronto_maple_leafs",
    "Senators": "ottawa_senators",
    "Ottawa Senators": "ottawa_senators",
    "Canadiens": "montreal_canadiens",
    "Montreal Canadiens": "montreal_canadiens",
    "Habs": "montreal_canadiens",
    "Bruins": "boston_bruins",
    "Boston Bruins": "boston_bruins",
    "Sabres": "buffalo_sabres",
    "Buffalo Sabres": "buffalo_sabres",
    "Rangers": "new_york_rangers",
    "New York Rangers": "new_york_rangers",
    "NY Rangers": "new_york_rangers",
    "Islanders": "new_york_islanders",
    "New York Islanders": "new_york_islanders",
    "NY Islanders": "new_york_islanders",
    "Devils": "new_jersey_devils",
    "New Jersey Devils": "new_jersey_devils",
    "NJ Devils": "new_jersey_devils",
    "Flyers": "philadelphia_flyers",
    "Philadelphia Flyers": "philadelphia_flyers",
    "Penguins": "pittsburgh_penguins",
    "Pittsburgh Penguins": "pittsburgh_penguins",
    "Capitals": "washington_capitals",
    "Washington Capitals": "washington_capitals",
    "Caps": "washington_capitals",
    "Hurricanes": "carolina_hurricanes",
    "Carolina Hurricanes": "carolina_hurricanes",
    "Canes": "carolina_hurricanes",
    "Panthers": "florida_panthers",
    "Florida Panthers": "florida_panthers",
    "Lightning": "tampa_bay_lightning",
    "Tampa Bay Lightning": "tampa_bay_lightning",
    "Bolts": "tampa_bay_lightning",
    "Red Wings": "detroit_red_wings",
    "Detroit Red Wings": "detroit_red_wings",
    "Blackhawks": "chicago_blackhawks",
    "Chicago Blackhawks": "chicago_blackhawks",
    "Blues": "st_louis_blues",
    "St. Louis Blues": "st_louis_blues",
    "Wild": "minnesota_wild",
    "Minnesota Wild": "minnesota_wild",
    "Jets": "winnipeg_jets",
    "Winnipeg Jets": "winnipeg_jets",
    "Avalanche": "colorado_avalanche",
    "Colorado Avalanche": "colorado_avalanche",
    "Avs": "colorado_avalanche",
    "Stars": "dallas_stars",
    "Dallas Stars": "dallas_stars",
    "Predators": "nashville_predators",
    "Nashville Predators": "nashville_predators",
    "Preds": "nashville_predators",
    "Coyotes": "arizona_coyotes",
    "Arizona Coyotes": "arizona_coyotes",
    "Golden Knights": "vegas_golden_knights",
    "Vegas Golden Knights": "vegas_golden_knights",
    "Knights": "vegas_golden_knights",
    "Kraken": "seattle_kraken",
    "Seattle Kraken": "seattle_kraken",
    "Sharks": "san_jose_sharks",
    "San Jose Sharks": "san_jose_sharks",
    "Kings": "los_angeles_kings",
    "Los Angeles Kings": "los_angeles_kings",
    "LA Kings": "los_angeles_kings",
    "Ducks": "anaheim_ducks",
    "Anaheim Ducks": "anaheim_ducks",
}
