"""NCAA (College Sports) team name mappings."""

# SEC Teams (Southeastern Conference)
SEC_TEAM_MAPPINGS = {
    "Alabama Crimson Tide": "alabama_crimson_tide",
    "Alabama": "alabama_crimson_tide",
    "Bama": "alabama_crimson_tide",
    "Arkansas Razorbacks": "arkansas_razorbacks",
    "Arkansas": "arkansas_razorbacks",
    "Hogs": "arkansas_razorbacks",
    "Auburn Tigers": "auburn_tigers",
    "Auburn": "auburn_tigers",
    "Florida Gators": "florida_gators",
    "Florida": "florida_gators",
    "UF": "florida_gators",
    "Georgia Bulldogs": "georgia_bulldogs",
    "Georgia": "georgia_bulldogs",
    "UGA": "georgia_bulldogs",
    "Kentucky Wildcats": "kentucky_wildcats",
    "Kentucky": "kentucky_wildcats",
    "UK": "kentucky_wildcats",
    "LSU Tigers": "lsu_tigers",
    "LSU": "lsu_tigers",
    "Louisiana State Tigers": "lsu_tigers",
    "Ole Miss Rebels": "ole_miss_rebels",
    "Ole Miss": "ole_miss_rebels",
    "Mississippi Rebels": "ole_miss_rebels",
    "Mississippi State Bulldogs": "mississippi_state_bulldogs",
    "Mississippi State": "mississippi_state_bulldogs",
    "MSU Bulldogs": "mississippi_state_bulldogs",
    "Missouri Tigers": "missouri_tigers",
    "Missouri": "missouri_tigers",
    "Mizzou": "missouri_tigers",
    "Oklahoma Sooners": "oklahoma_sooners",
    "Oklahoma": "oklahoma_sooners",
    "OU": "oklahoma_sooners",
    "South Carolina Gamecocks": "south_carolina_gamecocks",
    "South Carolina": "south_carolina_gamecocks",
    "Gamecocks": "south_carolina_gamecocks",
    "USC": "south_carolina_gamecocks",
    "Tennessee Volunteers": "tennessee_volunteers",
    "Tennessee": "tennessee_volunteers",
    "Vols": "tennessee_volunteers",
    "Texas Longhorns": "texas_longhorns",
    "Texas": "texas_longhorns",
    "UT": "texas_longhorns",
    "Texas A&M Aggies": "texas_a_and_m_aggies",
    "Texas A&M": "texas_a_and_m_aggies",
    "Aggies": "texas_a_and_m_aggies",
    "A&M": "texas_a_and_m_aggies",
    "Vanderbilt Commodores": "vanderbilt_commodores",
    "Vanderbilt": "vanderbilt_commodores",
    "Vandy": "vanderbilt_commodores",
}

# Big Ten Conference Teams
BIG_TEN_TEAM_MAPPINGS = {
    "Illinois Fighting Illini": "illinois_fighting_illini",
    "Illinois": "illinois_fighting_illini",
    "Fighting Illini": "illinois_fighting_illini",
    "Indiana Hoosiers": "indiana_hoosiers",
    "Indiana": "indiana_hoosiers",
    "IU": "indiana_hoosiers",
    "Iowa Hawkeyes": "iowa_hawkeyes",
    "Iowa": "iowa_hawkeyes",
    "Maryland Terrapins": "maryland_terrapins",
    "Maryland": "maryland_terrapins",
    "Terps": "maryland_terrapins",
    "Michigan Wolverines": "michigan_wolverines",
    "Michigan": "michigan_wolverines",
    "UM": "michigan_wolverines",
    "Michigan State Spartans": "michigan_state_spartans",
    "Michigan State": "michigan_state_spartans",
    "MSU Spartans": "michigan_state_spartans",
    "Minnesota Golden Gophers": "minnesota_golden_gophers",
    "Minnesota": "minnesota_golden_gophers",
    "Golden Gophers": "minnesota_golden_gophers",
    "Nebraska Cornhuskers": "nebraska_cornhuskers",
    "Nebraska": "nebraska_cornhuskers",
    "Huskers": "nebraska_cornhuskers",
    "UN": "nebraska_cornhuskers",
    "Northwestern Wildcats": "northwestern_wildcats",
    "Northwestern": "northwestern_wildcats",
    "NU": "northwestern_wildcats",
    "Ohio State Buckeyes": "ohio_state_buckeyes",
    "Ohio State": "ohio_state_buckeyes",
    "OSU Buckeyes": "ohio_state_buckeyes",
    "Oregon Ducks": "oregon_ducks",
    "Oregon": "oregon_ducks",
    "UO": "oregon_ducks",
    "Penn State Nittany Lions": "penn_state_nittany_lions",
    "Penn State": "penn_state_nittany_lions",
    "PSU": "penn_state_nittany_lions",
    "Purdue Boilermakers": "purdue_boilermakers",
    "Purdue": "purdue_boilermakers",
    "Rutgers Scarlet Knights": "rutgers_scarlet_knights",
    "Rutgers": "rutgers_scarlet_knights",
    "RU": "rutgers_scarlet_knights",
    "UCLA Bruins": "ucla_bruins",
    "UCLA": "ucla_bruins",
    "USC Trojans": "usc_trojans",
    "USC": "usc_trojans",
    "Southern California Trojans": "usc_trojans",
    "Washington Huskies": "washington_huskies",
    "Washington": "washington_huskies",
    "UW": "washington_huskies",
    "Wisconsin Badgers": "wisconsin_badgers",
    "Wisconsin": "wisconsin_badgers",
    "UW-Madison": "wisconsin_badgers",
}

# ACC Teams (Atlantic Coast Conference)
ACC_TEAM_MAPPINGS = {
    "Boston College Eagles": "boston_college_eagles",
    "Boston College": "boston_college_eagles",
    "BC Eagles": "boston_college_eagles",
    "California Golden Bears": "california_golden_bears",
    "Cal": "california_golden_bears",
    "California": "california_golden_bears",
    "Clemson Tigers": "clemson_tigers",
    "Clemson": "clemson_tigers",
    "Duke Blue Devils": "duke_blue_devils",
    "Duke": "duke_blue_devils",
    "Florida State Seminoles": "florida_state_seminoles",
    "Florida State": "florida_state_seminoles",
    "FSU": "florida_state_seminoles",
    "Georgia Tech Yellow Jackets": "georgia_tech_yellow_jackets",
    "Georgia Tech": "georgia_tech_yellow_jackets",
    "GT": "georgia_tech_yellow_jackets",
    "Louisville Cardinals": "louisville_cardinals",
    "Louisville": "louisville_cardinals",
    "Miami Hurricanes": "miami_hurricanes",
    "Miami (FL)": "miami_hurricanes",
    "The U": "miami_hurricanes",
    "Miami FL": "miami_hurricanes",
    "North Carolina Tar Heels": "north_carolina_tar_heels",
    "North Carolina": "north_carolina_tar_heels",
    "UNC": "north_carolina_tar_heels",
    "NC State Wolfpack": "nc_state_wolfpack",
    "NC State": "nc_state_wolfpack",
    "North Carolina State Wolfpack": "nc_state_wolfpack",
    "Notre Dame Fighting Irish": "notre_dame_fighting_irish",
    "Notre Dame": "notre_dame_fighting_irish",
    "ND": "notre_dame_fighting_irish",
    "Pittsburgh Panthers": "pittsburgh_panthers",
    "Pittsburgh": "pittsburgh_panthers",
    "Pitt": "pittsburgh_panthers",
    "SMU Mustangs": "smu_mustangs",
    "SMU": "smu_mustangs",
    "Stanford Cardinal": "stanford_cardinal",
    "Stanford": "stanford_cardinal",
    "Syracuse Orange": "syracuse_orange",
    "Syracuse": "syracuse_orange",
    "Virginia Cavaliers": "virginia_cavaliers",
    "Virginia": "virginia_cavaliers",
    "UVA": "virginia_cavaliers",
    "Virginia Tech Hokies": "virginia_tech_hokies",
    "Virginia Tech": "virginia_tech_hokies",
    "VT": "virginia_tech_hokies",
    "Wake Forest Demon Deacons": "wake_forest_demon_deacons",
    "Wake Forest": "wake_forest_demon_deacons",
    "WF": "wake_forest_demon_deacons",
}

# Big 12 Conference Teams
BIG_12_TEAM_MAPPINGS = {
    "Arizona State Sun Devils": "arizona_state_sun_devils",
    "Arizona State": "arizona_state_sun_devils",
    "ASU": "arizona_state_sun_devils",
    "Arizona Wildcats": "arizona_wildcats",
    "Arizona": "arizona_wildcats",
    "Baylor Bears": "baylor_bears",
    "Baylor": "baylor_bears",
    "BYU Cougars": "byu_cougars",
    "BYU": "byu_cougars",
    "Brigham Young Cougars": "byu_cougars",
    "Cincinnati Bearcats": "cincinnati_bearcats",
    "Cincinnati": "cincinnati_bearcats",
    "Colorado Buffaloes": "colorado_buffaloes",
    "Colorado": "colorado_buffaloes",
    "Buffs": "colorado_buffaloes",
    "Houston Cougars": "houston_cougars",
    "Houston": "houston_cougars",
    "Iowa State Cyclones": "iowa_state_cyclones",
    "Iowa State": "iowa_state_cyclones",
    "ISU": "iowa_state_cyclones",
    "Kansas Jayhawks": "kansas_jayhawks",
    "Kansas": "kansas_jayhawks",
    "KU": "kansas_jayhawks",
    "Kansas State Wildcats": "kansas_state_wildcats",
    "Kansas State": "kansas_state_wildcats",
    "KSU": "kansas_state_wildcats",
    "Oklahoma State Cowboys": "oklahoma_state_cowboys",
    "Oklahoma State": "oklahoma_state_cowboys",
    "OSU Cowboys": "oklahoma_state_cowboys",
    "OK State": "oklahoma_state_cowboys",
    "TCU Horned Frogs": "tcu_horned_frogs",
    "TCU": "tcu_horned_frogs",
    "Texas Christian Horned Frogs": "tcu_horned_frogs",
    "Texas Tech Red Raiders": "texas_tech_red_raiders",
    "Texas Tech": "texas_tech_red_raiders",
    "TTU": "texas_tech_red_raiders",
    "UCF Knights": "ucf_knights",
    "UCF": "ucf_knights",
    "Central Florida Knights": "ucf_knights",
    "Utah Utes": "utah_utes",
    "Utah": "utah_utes",
    "West Virginia Mountaineers": "west_virginia_mountaineers",
    "West Virginia": "west_virginia_mountaineers",
    "WVU": "west_virginia_mountaineers",
}

# American Athletic Conference (AAC) Teams
AAC_TEAM_MAPPINGS = {
    "Charlotte 49ers": "charlotte_49ers",
    "Charlotte": "charlotte_49ers",
    "UNC Charlotte": "charlotte_49ers",
    "East Carolina Pirates": "east_carolina_pirates",
    "East Carolina": "east_carolina_pirates",
    "ECU": "east_carolina_pirates",
    "Florida Atlantic Owls": "florida_atlantic_owls",
    "Florida Atlantic": "florida_atlantic_owls",
    "FAU": "florida_atlantic_owls",
    "Memphis Tigers": "memphis_tigers",
    "Memphis": "memphis_tigers",
    "Navy Midshipmen": "navy_midshipmen",
    "Navy": "navy_midshipmen",
    "Naval Academy": "navy_midshipmen",
    "North Texas Mean Green": "north_texas_mean_green",
    "North Texas": "north_texas_mean_green",
    "UNT": "north_texas_mean_green",
    "Rice Owls": "rice_owls",
    "Rice": "rice_owls",
    "South Florida Bulls": "south_florida_bulls",
    "South Florida": "south_florida_bulls",
    "USF": "south_florida_bulls",
    "Temple Owls": "temple_owls",
    "Temple": "temple_owls",
    "Tulane Green Wave": "tulane_green_wave",
    "Tulane": "tulane_green_wave",
    "Tulsa Golden Hurricane": "tulsa_golden_hurricane",
    "Tulsa": "tulsa_golden_hurricane",
    "UAB Blazers": "uab_blazers",
    "UAB": "uab_blazers",
    "Alabama-Birmingham": "uab_blazers",
    "UTSA Roadrunners": "utsa_roadrunners",
    "UTSA": "utsa_roadrunners",
    "Texas-San Antonio": "utsa_roadrunners",
    "Wichita State Shockers": "wichita_state_shockers",
    "Wichita State": "wichita_state_shockers",
}

# Conference USA (C-USA) Teams
CUSA_TEAM_MAPPINGS = {
    "Florida International Panthers": "florida_international_panthers",
    "FIU": "florida_international_panthers",
    "Florida International": "florida_international_panthers",
    "Jacksonville State Gamecocks": "jacksonville_state_gamecocks",
    "Jacksonville State": "jacksonville_state_gamecocks",
    "JSU": "jacksonville_state_gamecocks",
    "Kennesaw State Owls": "kennesaw_state_owls",
    "Kennesaw State": "kennesaw_state_owls",
    "Liberty Flames": "liberty_flames",
    "Liberty": "liberty_flames",
    "Louisiana Tech Bulldogs": "louisiana_tech_bulldogs",
    "Louisiana Tech": "louisiana_tech_bulldogs",
    "LA Tech": "louisiana_tech_bulldogs",
    "Middle Tennessee Blue Raiders": "middle_tennessee_blue_raiders",
    "Middle Tennessee": "middle_tennessee_blue_raiders",
    "MTSU": "middle_tennessee_blue_raiders",
    "New Mexico State Aggies": "new_mexico_state_aggies",
    "New Mexico State": "new_mexico_state_aggies",
    "NMSU": "new_mexico_state_aggies",
    "Sam Houston Bearkats": "sam_houston_bearkats",
    "Sam Houston": "sam_houston_bearkats",
    "SHSU": "sam_houston_bearkats",
    "UTEP Miners": "utep_miners",
    "UTEP": "utep_miners",
    "Texas-El Paso": "utep_miners",
    "Western Kentucky Hilltoppers": "western_kentucky_hilltoppers",
    "Western Kentucky": "western_kentucky_hilltoppers",
    "WKU": "western_kentucky_hilltoppers",
}

# Mountain West Conference Teams
MWC_TEAM_MAPPINGS = {
    "Air Force Falcons": "air_force_falcons",
    "Air Force": "air_force_falcons",
    "Boise State Broncos": "boise_state_broncos",
    "Boise State": "boise_state_broncos",
    "Colorado State Rams": "colorado_state_rams",
    "Colorado State": "colorado_state_rams",
    "CSU": "colorado_state_rams",
    "Fresno State Bulldogs": "fresno_state_bulldogs",
    "Fresno State": "fresno_state_bulldogs",
    "Hawaii Rainbow Warriors": "hawaii_rainbow_warriors",
    "Hawaii": "hawaii_rainbow_warriors",
    "UH": "hawaii_rainbow_warriors",
    "Nevada Wolf Pack": "nevada_wolf_pack",
    "Nevada": "nevada_wolf_pack",
    "UNR": "nevada_wolf_pack",
    "New Mexico Lobos": "new_mexico_lobos",
    "New Mexico": "new_mexico_lobos",
    "UNM": "new_mexico_lobos",
    "San Diego State Aztecs": "san_diego_state_aztecs",
    "San Diego State": "san_diego_state_aztecs",
    "SDSU": "san_diego_state_aztecs",
    "San Jose State Spartans": "san_jose_state_spartans",
    "San Jose State": "san_jose_state_spartans",
    "SJSU": "san_jose_state_spartans",
    "UNLV Rebels": "unlv_rebels",
    "UNLV": "unlv_rebels",
    "Nevada-Las Vegas": "unlv_rebels",
    "Utah State Aggies": "utah_state_aggies",
    "Utah State": "utah_state_aggies",
    "USU": "utah_state_aggies",
    "Wyoming Cowboys": "wyoming_cowboys",
    "Wyoming": "wyoming_cowboys",
}

# Sun Belt Conference Teams
SUN_BELT_TEAM_MAPPINGS = {
    "Appalachian State Mountaineers": "appalachian_state_mountaineers",
    "Appalachian State": "appalachian_state_mountaineers",
    "App State": "appalachian_state_mountaineers",
    "Arkansas State Red Wolves": "arkansas_state_red_wolves",
    "Arkansas State": "arkansas_state_red_wolves",
    "A-State": "arkansas_state_red_wolves",
    "Coastal Carolina Chanticleers": "coastal_carolina_chanticleers",
    "Coastal Carolina": "coastal_carolina_chanticleers",
    "CCU": "coastal_carolina_chanticleers",
    "Georgia Southern Eagles": "georgia_southern_eagles",
    "Georgia Southern": "georgia_southern_eagles",
    "GSU": "georgia_southern_eagles",
    "Georgia State Panthers": "georgia_state_panthers",
    "Georgia State": "georgia_state_panthers",
    "James Madison Dukes": "james_madison_dukes",
    "James Madison": "james_madison_dukes",
    "JMU": "james_madison_dukes",
    "Louisiana Ragin' Cajuns": "louisiana_ragin_cajuns",
    "Louisiana": "louisiana_ragin_cajuns",
    "UL Lafayette": "louisiana_ragin_cajuns",
    "Louisiana-Monroe Warhawks": "louisiana_monroe_warhawks",
    "Louisiana-Monroe": "louisiana_monroe_warhawks",
    "ULM": "louisiana_monroe_warhawks",
    "Marshall Thundering Herd": "marshall_thundering_herd",
    "Marshall": "marshall_thundering_herd",
    "Old Dominion Monarchs": "old_dominion_monarchs",
    "Old Dominion": "old_dominion_monarchs",
    "ODU": "old_dominion_monarchs",
    "South Alabama Jaguars": "south_alabama_jaguars",
    "South Alabama": "south_alabama_jaguars",
    "USA": "south_alabama_jaguars",
    "Southern Miss Golden Eagles": "southern_miss_golden_eagles",
    "Southern Miss": "southern_miss_golden_eagles",
    "USM": "southern_miss_golden_eagles",
    "Texas State Bobcats": "texas_state_bobcats",
    "Texas State": "texas_state_bobcats",
    "TXST": "texas_state_bobcats",
    "Troy Trojans": "troy_trojans",
    "Troy": "troy_trojans",
}

# Mid-American Conference (MAC) Teams
MAC_TEAM_MAPPINGS = {
    "Akron Zips": "akron_zips",
    "Akron": "akron_zips",
    "Ball State Cardinals": "ball_state_cardinals",
    "Ball State": "ball_state_cardinals",
    "Bowling Green Falcons": "bowling_green_falcons",
    "Bowling Green": "bowling_green_falcons",
    "BGSU": "bowling_green_falcons",
    "Buffalo Bulls": "buffalo_bulls",
    "Buffalo": "buffalo_bulls",
    "UB": "buffalo_bulls",
    "Central Michigan Chippewas": "central_michigan_chippewas",
    "Central Michigan": "central_michigan_chippewas",
    "CMU": "central_michigan_chippewas",
    "Eastern Michigan Eagles": "eastern_michigan_eagles",
    "Eastern Michigan": "eastern_michigan_eagles",
    "EMU": "eastern_michigan_eagles",
    "Kent State Golden Flashes": "kent_state_golden_flashes",
    "Kent State": "kent_state_golden_flashes",
    "Miami RedHawks": "miami_redhawks",
    "Miami (OH)": "miami_redhawks",
    "Miami Ohio": "miami_redhawks",
    "Northern Illinois Huskies": "northern_illinois_huskies",
    "Northern Illinois": "northern_illinois_huskies",
    "NIU": "northern_illinois_huskies",
    "Ohio Bobcats": "ohio_bobcats",
    "Ohio": "ohio_bobcats",
    "Toledo Rockets": "toledo_rockets",
    "Toledo": "toledo_rockets",
    "Western Michigan Broncos": "western_michigan_broncos",
    "Western Michigan": "western_michigan_broncos",
    "WMU": "western_michigan_broncos",
}
