"""MLB (Baseball) team name mappings."""

# MLB Teams (Baseball)
MLB_TEAM_MAPPINGS = {
    "Diamondbacks": "arizona_diamondbacks",
    "Arizona Diamondbacks": "arizona_diamondbacks",
    "D-backs": "arizona_diamondbacks",
    "Braves": "atlanta_braves",
    "Atlanta Braves": "atlanta_braves",
    "Orioles": "baltimore_orioles",
    "Baltimore Orioles": "baltimore_orioles",
    "Red Sox": "boston_red_sox",
    "Boston Red Sox": "boston_red_sox",
    "Cubs": "chicago_cubs",
    "Chicago Cubs": "chicago_cubs",
    "White Sox": "chicago_white_sox",
    "Chicago White Sox": "chicago_white_sox",
    "Reds": "cincinnati_reds",
    "Cincinnati Reds": "cincinnati_reds",
    "Guardians": "cleveland_guardians",
    "Cleveland Guardians": "cleveland_guardians",
    "Rockies": "colorado_rockies",
    "Colorado Rockies": "colorado_rockies",
    "Tigers": "detroit_tigers",
    "Detroit Tigers": "detroit_tigers",
    "Astros": "houston_astros",
    "Houston Astros": "houston_astros",
    "Royals": "kansas_city_royals",
    "Kansas City Royals": "kansas_city_royals",
    "Angels": "los_angeles_angels",
    "Los Angeles Angels": "los_angeles_angels",
    "LA Angels": "los_angeles_angels",
    "Dodgers": "los_angeles_dodgers",
    "Los Angeles Dodgers": "los_angeles_dodgers",
    "LA Dodgers": "los_angeles_dodgers",
    "Marlins": "miami_marlins",
    "Miami Marlins": "miami_marlins",
    "Brewers": "milwaukee_brewers",
    "Milwaukee Brewers": "milwaukee_brewers",
    "Twins": "minnesota_twins",
    "Minnesota Twins": "minnesota_twins",
    "Mets": "new_york_mets",
    "New York Mets": "new_york_mets",
    "NY Mets": "new_york_mets",
    "Yankees": "new_york_yankees",
    "New York Yankees": "new_york_yankees",
    "NY Yankees": "new_york_yankees",
    "Athletics": "oakland_athletics",
    "Oakland Athletics": "oakland_athletics",
    "A's": "oakland_athletics",
    "Phillies": "philadelphia_phillies",
    "Philadelphia Phillies": "philadelphia_phillies",
    "Pirates": "pittsburgh_pirates",
    "Pittsburgh Pirates": "pittsburgh_pirates",
    "Padres": "san_diego_padres",
    "San Diego Padres": "san_diego_padres",
    "Giants": "san_francisco_giants",
    "San Francisco Giants": "san_francisco_giants",
    "SF Giants": "san_francisco_giants",
    "Mariners": "seattle_mariners",
    "Seattle Mariners": "seattle_mariners",
    "Cardinals": "st_louis_cardinals",
    "St. Louis Cardinals": "st_louis_cardinals",
    "Rays": "tampa_bay_rays",
    "Tampa Bay Rays": "tampa_bay_rays",
    "Rangers": "texas_rangers",
    "Texas Rangers": "texas_rangers",
    "Blue Jays": "toronto_blue_jays",
    "Toronto Blue Jays": "toronto_blue_jays",
    "Nationals": "washington_nationals",
    "Washington Nationals": "washington_nationals",
}
