"""NBA (Basketball) team name mappings."""

# NBA Teams (Basketball)
NBA_TEAM_MAPPINGS = {
    "Hawks": "atlanta_hawks",
    "Atlanta Hawks": "atlanta_hawks",
    "Celtics": "boston_celtics",
    "Boston Celtics": "boston_celtics",
    "Nets": "brooklyn_nets",
    "Brooklyn Nets": "brooklyn_nets",
    "Hornets": "charlotte_hornets",
    "Charlotte Hornets": "charlotte_hornets",
    "Bulls": "chicago_bulls",
    "Chicago Bulls": "chicago_bulls",
    "Cavaliers": "cleveland_cavaliers",
    "Cleveland Cavaliers": "cleveland_cavaliers",
    "Cavs": "cleveland_cavaliers",
    "Mavericks": "dallas_mavericks",
    "Dallas Mavericks": "dallas_mavericks",
    "Mavs": "dallas_mavericks",
    "Nuggets": "denver_nuggets",
    "Denver Nuggets": "denver_nuggets",
    "Pistons": "detroit_pistons",
    "Detroit Pistons": "detroit_pistons",
    "Warriors": "golden_state_warriors",
    "Golden State Warriors": "golden_state_warriors",
    "Rockets": "houston_rockets",
    "Houston Rockets": "houston_rockets",
    "Pacers": "indiana_pacers",
    "Indiana Pacers": "indiana_pacers",
    "Clippers": "los_angeles_clippers",
    "Los Angeles Clippers": "los_angeles_clippers",
    "LA Clippers": "los_angeles_clippers",
    "Lakers": "los_angeles_lakers",
    "Los Angeles Lakers": "los_angeles_lakers",
    "LA Lakers": "los_angeles_lakers",
    "Grizzlies": "memphis_grizzlies",
    "Memphis Grizzlies": "memphis_grizzlies",
    "Heat": "miami_heat",
    "Miami Heat": "miami_heat",
    "Bucks": "milwaukee_bucks",
    "Milwaukee Bucks": "milwaukee_bucks",
    "Timberwolves": "minnesota_timberwolves",
    "Minnesota Timberwolves": "minnesota_timberwolves",
    "Wolves": "minnesota_timberwolves",
    "Pelicans": "new_orleans_pelicans",
    "New Orleans Pelicans": "new_orleans_pelicans",
    "Knicks": "new_york_knicks",
    "New York Knicks": "new_york_knicks",
    "NY Knicks": "new_york_knicks",
    "Thunder": "oklahoma_city_thunder",
    "Oklahoma City Thunder": "oklahoma_city_thunder",
    "OKC Thunder": "oklahoma_city_thunder",
    "Magic": "orlando_magic",
    "Orlando Magic": "orlando_magic",
    "76ers": "philadelphia_76ers",
    "Philadelphia 76ers": "philadelphia_76ers",
    "Sixers": "philadelphia_76ers",
    "Suns": "phoenix_suns",
    "Phoenix Suns": "phoenix_suns",
    "Trail Blazers": "portland_trail_blazers",
    "Portland Trail Blazers": "portland_trail_blazers",
    "Blazers": "portland_trail_blazers",
    "Kings": "sacramento_kings",
    "Sacramento Kings": "sacramento_kings",
    "Spurs": "san_antonio_spurs",
    "San Antonio Spurs": "san_antonio_spurs",
    "Raptors": "toronto_raptors",
    "Toronto Raptors": "toronto_raptors",
    "Jazz": "utah_jazz",
    "Utah Jazz": "utah_jazz",
    "Wizards": "washington_wizards",
    "Washington Wizards": "washington_wizards",
}
