"""NFL (American Football) team name mappings."""

# NFL Teams (American Football)
NFL_TEAM_MAPPINGS = {
    "49ers": "san_francisco_49ers",
    "SF 49ers": "san_francisco_49ers",
    "Bears": "chicago_bears",
    "Chicago Bears": "chicago_bears",
    "Bengals": "cincinnati_bengals",
    "Cincinnati Bengals": "cincinnati_bengals",
    "Bills": "buffalo_bills",
    "Buffalo Bills": "buffalo_bills",
    "Broncos": "denver_broncos",
    "Denver Broncos": "denver_broncos",
    "Browns": "cleveland_browns",
    "Cleveland Browns": "cleveland_browns",
    "Buccaneers": "tampa_bay_buccaneers",
    "Tampa Bay Buccaneers": "tampa_bay_buccaneers",
    "Cardinals": "arizona_cardinals",
    "Arizona Cardinals": "arizona_cardinals",
    "Chargers": "los_angeles_chargers",
    "Los Angeles Chargers": "los_angeles_chargers",
    "LA Chargers": "los_angeles_chargers",
    "Chiefs": "kansas_city_chiefs",
    "Kansas City Chiefs": "kansas_city_chiefs",
    "Colts": "indianapolis_colts",
    "Indianapolis Colts": "indianapolis_colts",
    "Cowboys": "dallas_cowboys",
    "Dallas Cowboys": "dallas_cowboys",
    "Dolphins": "miami_dolphins",
    "Miami Dolphins": "miami_dolphins",
    "Eagles": "philadelphia_eagles",
    "Philadelphia Eagles": "philadelphia_eagles",
    "Falcons": "atlanta_falcons",
    "Atlanta Falcons": "atlanta_falcons",
    "Giants": "new_york_giants",
    "New York Giants": "new_york_giants",
    "NY Giants": "new_york_giants",
    "Jaguars": "jacksonville_jaguars",
    "Jacksonville Jaguars": "jacksonville_jaguars",
    "Jets": "new_york_jets",
    "New York Jets": "new_york_jets",
    "NY Jets": "new_york_jets",
    "Lions": "detroit_lions",
    "Detroit Lions": "detroit_lions",
    "Packers": "green_bay_packers",
    "Green Bay Packers": "green_bay_packers",
    "Panthers": "carolina_panthers",
    "Carolina Panthers": "carolina_panthers",
    "Patriots": "new_england_patriots",
    "New England Patriots": "new_england_patriots",
    "Raiders": "las_vegas_raiders",
    "Las Vegas Raiders": "las_vegas_raiders",
    "Rams": "los_angeles_rams",
    "Los Angeles Rams": "los_angeles_rams",
    "LA Rams": "los_angeles_rams",
    "Ravens": "baltimore_ravens",
    "Baltimore Ravens": "baltimore_ravens",
    "Saints": "new_orleans_saints",
    "New Orleans Saints": "new_orleans_saints",
    "Seahawks": "seattle_seahawks",
    "Seattle Seahawks": "seattle_seahawks",
    "Steelers": "pittsburgh_steelers",
    "Pittsburgh Steelers": "pittsburgh_steelers",
    "Texans": "houston_texans",
    "Houston Texans": "houston_texans",
    "Titans": "tennessee_titans",
    "Tennessee Titans": "tennessee_titans",
    "Vikings": "minnesota_vikings",
    "Minnesota Vikings": "minnesota_vikings",
    "Commanders": "washington_commanders",
    "Washington Commanders": "washington_commanders",
}
