"""Other sports team name mappings."""

# CFL Teams (Canadian Football League)
CFL_TEAM_MAPPINGS = {
    "BC Lions": "bc_lions",
    "Calgary Stampeders": "calgary_stampeders",
    "Stampeders": "calgary_stampeders",
    "Edmonton Elks": "edmonton_elks",
    "Hamilton Tiger-Cats": "hamilton_tiger_cats",
    "Tiger-Cats": "hamilton_tiger_cats",
    "Ti-Cats": "hamilton_tiger_cats",
    "Montreal Alouettes": "montreal_alouettes",
    "Alouettes": "montreal_alouettes",
    "Ottawa Redblacks": "ottawa_redblacks",
    "Redblacks": "ottawa_redblacks",
    "Saskatchewan Roughriders": "saskatchewan_roughriders",
    "Roughriders": "saskatchewan_roughriders",
    "Toronto Argonauts": "toronto_argonauts",
    "Argonauts": "toronto_argonauts",
    "Argos": "toronto_argonauts",
    "Winnipeg Blue Bombers": "winnipeg_blue_bombers",
    "Blue Bombers": "winnipeg_blue_bombers",
    "Bombers": "winnipeg_blue_bombers",
}

# WNBA Teams
WNBA_TEAM_MAPPINGS = {
    "Atlanta Dream": "atlanta_dream",
    "Chicago Sky": "chicago_sky",
    "Connecticut Sun": "connecticut_sun",
    "Dallas Wings": "dallas_wings",
    "Indiana Fever": "indiana_fever",
    "Las Vegas Aces": "las_vegas_aces",
    "Aces": "las_vegas_aces",
    "Los Angeles Sparks": "los_angeles_sparks",
    "LA Sparks": "los_angeles_sparks",
    "Minnesota Lynx": "minnesota_lynx",
    "New York Liberty": "new_york_liberty",
    "NY Liberty": "new_york_liberty",
    "Phoenix Mercury": "phoenix_mercury",
    "Seattle Storm": "seattle_storm",
    "Washington Mystics": "washington_mystics",
    "Golden State Valkyries": "golden_state_valkyries",
}

# EuroLeague Teams (Basketball)
EUROLEAGUE_TEAM_MAPPINGS = {
    "Alba Berlin": "alba_berlin",
    "Anadolu Efes Istanbul": "anadolu_efes_istanbul",
    "Anadolu Efes": "anadolu_efes_istanbul",
    "AS Monaco Basket": "as_monaco_basket",
    "Baskonia Vitoria-Gasteiz": "baskonia_vitoria_gasteiz",
    "Baskonia": "baskonia_vitoria_gasteiz",
    "Crvena Zvezda Meridianbet Belgrade": "crvena_zvezda_belgrade",
    "Crvena Zvezda": "crvena_zvezda_belgrade",
    "EA7 Emporio Armani Milan": "olimpia_milano",
    "Olimpia Milano": "olimpia_milano",
    "AX Armani Exchange Milan": "olimpia_milano",
    "FC Barcelona Bàsquet": "fc_barcelona_basquet",
    "FC Bayern Munich Basketball": "fc_bayern_munich_basketball",
    "Fenerbahçe Beko Istanbul": "fenerbahce_beko_istanbul",
    "Fenerbahce": "fenerbahce_beko_istanbul",
    "LDLC ASVEL Villeurbanne": "asvel_basket",
    "ASVEL": "asvel_basket",
    "Maccabi Playtika Tel Aviv": "maccabi_tel_aviv",
    "Maccabi Tel Aviv": "maccabi_tel_aviv",
    "Olympiacos Piraeus": "olympiacos_piraeus",
    "Olympiacos": "olympiacos_piraeus",
    "Panathinaikos AKTOR Athens": "panathinaikos_athens",
    "Panathinaikos": "panathinaikos_athens",
    "Partizan Mozzart Bet Belgrade": "partizan_belgrade",
    "Partizan": "partizan_belgrade",
    "Real Madrid Baloncesto": "real_madrid_baloncesto",
    "Valencia Basket": "valencia_basket",
    "Virtus Segafredo Bologna": "virtus_bologna",
    "Virtus Bologna": "virtus_bologna",
    "Žalgiris Kaunas": "zalgiris_kaunas",
    "Zalgiris Kaunas": "zalgiris_kaunas",
    "Zalgiris": "zalgiris_kaunas",
    "Paris Basketball": "paris_basketball",
}

# NPB Teams (Nippon Professional Baseball)
NPB_TEAM_MAPPINGS = {
    # Central League
    "Yomiuri Giants": "yomiuri_giants",
    "Hanshin Tigers": "hanshin_tigers",
    "Tokyo Yakult Swallows": "tokyo_yakult_swallows",
    "Yakult Swallows": "tokyo_yakult_swallows",
    "Yokohama DeNA BayStars": "yokohama_dena_baystars",
    "DeNA BayStars": "yokohama_dena_baystars",
    "Hiroshima Toyo Carp": "hiroshima_toyo_carp",
    "Hiroshima Carp": "hiroshima_toyo_carp",
    "Chunichi Dragons": "chunichi_dragons",
    # Pacific League
    "Orix Buffaloes": "orix_buffaloes",
    "Fukuoka SoftBank Hawks": "fukuoka_softbank_hawks",
    "SoftBank Hawks": "fukuoka_softbank_hawks",
    "Saitama Seibu Lions": "saitama_seibu_lions",
    "Seibu Lions": "saitama_seibu_lions",
    "Tohoku Rakuten Golden Eagles": "tohoku_rakuten_golden_eagles",
    "Rakuten Eagles": "tohoku_rakuten_golden_eagles",
    "Chiba Lotte Marines": "chiba_lotte_marines",
    "Hokkaido Nippon-Ham Fighters": "hokkaido_nippon_ham_fighters",
    "Nippon-Ham Fighters": "hokkaido_nippon_ham_fighters",
}

# KBO Teams (Korea Baseball Organization)
KBO_TEAM_MAPPINGS = {
    "Doosan Bears": "doosan_bears",
    "Hanwha Eagles": "hanwha_eagles",
    "Kia Tigers": "kia_tigers",
    "KIA Tigers": "kia_tigers",
    "Kiwoom Heroes": "kiwoom_heroes",
    "KT Wiz": "kt_wiz",
    "LG Twins": "lg_twins",
    "Lotte Giants": "lotte_giants",
    "NC Dinos": "nc_dinos",
    "Samsung Lions": "samsung_lions",
    "SSG Landers": "ssg_landers",
}

# AFL Teams (Australian Football League)
AFL_TEAM_MAPPINGS = {
    "Adelaide Crows": "adelaide_crows",
    "Adelaide": "adelaide_crows",
    "Brisbane Lions": "brisbane_lions",
    "Brisbane": "brisbane_lions",
    "Carlton Blues": "carlton_blues",
    "Carlton": "carlton_blues",
    "Collingwood Magpies": "collingwood_magpies",
    "Collingwood": "collingwood_magpies",
    "Essendon Bombers": "essendon_bombers",
    "Essendon": "essendon_bombers",
    "Fremantle Dockers": "fremantle_dockers",
    "Fremantle": "fremantle_dockers",
    "Geelong Cats": "geelong_cats",
    "Geelong": "geelong_cats",
    "Gold Coast Suns": "gold_coast_suns",
    "Gold Coast": "gold_coast_suns",
    "GWS Giants": "gws_giants",
    "Greater Western Sydney Giants": "gws_giants",
    "Hawthorn Hawks": "hawthorn_hawks",
    "Hawthorn": "hawthorn_hawks",
    "Melbourne Demons": "melbourne_demons",
    "Melbourne": "melbourne_demons",
    "North Melbourne Kangaroos": "north_melbourne_kangaroos",
    "North Melbourne": "north_melbourne_kangaroos",
    "Kangaroos": "north_melbourne_kangaroos",
    "Port Adelaide Power": "port_adelaide_power",
    "Port Adelaide": "port_adelaide_power",
    "Richmond Tigers": "richmond_tigers",
    "Richmond": "richmond_tigers",
    "St Kilda Saints": "st_kilda_saints",
    "St Kilda": "st_kilda_saints",
    "Sydney Swans": "sydney_swans",
    "Sydney": "sydney_swans",
    "West Coast Eagles": "west_coast_eagles",
    "West Coast": "west_coast_eagles",
    "Western Bulldogs": "western_bulldogs",
    "Bulldogs": "western_bulldogs",
    "Tasmania Devils": "tasmania_devils",
}

# Formula 1 Teams
F1_TEAM_MAPPINGS = {
    "Mercedes-AMG Petronas": "mercedes_amg_petronas",
    "Mercedes": "mercedes_amg_petronas",
    "Oracle Red Bull Racing": "red_bull_racing",
    "Red Bull": "red_bull_racing",
    "Scuderia Ferrari": "scuderia_ferrari",
    "Ferrari": "scuderia_ferrari",
    "McLaren Formula 1 Team": "mclaren_f1_team",
    "McLaren": "mclaren_f1_team",
    "Aston Martin Aramco Formula One Team": "aston_martin_f1_team",
    "Aston Martin": "aston_martin_f1_team",
    "BWT Alpine F1 Team": "alpine_f1_team",
    "Alpine": "alpine_f1_team",
    "Williams Racing": "williams_racing",
    "Williams": "williams_racing",
    "Visa Cash App RB Formula One Team": "visa_cash_app_rb",
    "VCARB": "visa_cash_app_rb",
    "RB": "visa_cash_app_rb",
    "Stake F1 Team Kick Sauber": "kick_sauber",
    "Sauber": "kick_sauber",
    "MoneyGram Haas F1 Team": "haas_f1_team",
    "Haas": "haas_f1_team",
}

# KHL Teams (Kontinental Hockey League)
KHL_TEAM_MAPPINGS = {
    "Ak Bars Kazan": "ak_bars_kazan",
    "Ak Bars": "ak_bars_kazan",
    "Amur Khabarovsk": "amur_khabarovsk",
    "Amur": "amur_khabarovsk",
    "Avangard Omsk": "avangard_omsk",
    "Avangard": "avangard_omsk",
    "Avtomobilist Yekaterinburg": "avtomobilist_yekaterinburg",
    "Avtomobilist": "avtomobilist_yekaterinburg",
    "Barys Nur-Sultan": "barys_nur_sultan",
    "Barys Astana": "barys_nur_sultan",
    "Barys": "barys_nur_sultan",
    "CSKA Moscow": "cska_moscow",
    "CSKA Moskva": "cska_moscow",
    "Dinamo Minsk": "dinamo_minsk",
    "Dinamo Riga": "dinamo_riga",
    "Dynamo Moscow": "dynamo_moscow",
    "Dynamo Moskva": "dynamo_moscow",
    "Jokerit Helsinki": "jokerit_helsinki",
    "Jokerit": "jokerit_helsinki",
    "Kunlun Red Star": "kunlun_red_star",
    "Lokomotiv Yaroslavl": "lokomotiv_yaroslavl",
    "Lokomotiv": "lokomotiv_yaroslavl",
    "Metallurg Magnitogorsk": "metallurg_magnitogorsk",
    "Metallurg Mg": "metallurg_magnitogorsk",
    "Neftekhimik Nizhnekamsk": "neftekhimik_nizhnekamsk",
    "Neftekhimik": "neftekhimik_nizhnekamsk",
    "Salavat Yulaev Ufa": "salavat_yulaev_ufa",
    "Salavat Yulaev": "salavat_yulaev_ufa",
    "Severstal Cherepovets": "severstal_cherepovets",
    "Severstal": "severstal_cherepovets",
    "Sibir Novosibirsk": "sibir_novosibirsk",
    "Sibir": "sibir_novosibirsk",
    "SKA Saint Petersburg": "ska_saint_petersburg",
    "SKA St. Petersburg": "ska_saint_petersburg",
    "SKA": "ska_saint_petersburg",
    "HC Sochi": "hc_sochi",
    "Sochi": "hc_sochi",
    "Spartak Moscow": "spartak_moscow",
    "Spartak Moskva": "spartak_moscow",
    "Torpedo Nizhny Novgorod": "torpedo_nizhny_novgorod",
    "Torpedo": "torpedo_nizhny_novgorod",
    "Traktor Chelyabinsk": "traktor_chelyabinsk",
    "Traktor": "traktor_chelyabinsk",
    "Vityaz Moscow Region": "vityaz_moscow_region",
    "Vityaz Podolsk": "vityaz_moscow_region",
    "Vityaz": "vityaz_moscow_region",
    "Lada Togliatti": "lada_togliatti",
}
