"""Soccer team name mappings for various leagues."""

# MLS Teams (Major League Soccer)
MLS_TEAM_MAPPINGS = {
    "Atlanta United FC": "atlanta_united_fc",
    "Atlanta United": "atlanta_united_fc",
    "Austin FC": "austin_fc",
    "Charlotte FC": "charlotte_fc",
    "Chicago Fire FC": "chicago_fire_fc",
    "Chicago Fire": "chicago_fire_fc",
    "FC Cincinnati": "fc_cincinnati",
    "Colorado Rapids": "colorado_rapids",
    "Columbus Crew": "columbus_crew",
    "D.C. United": "dc_united",
    "DC United": "dc_united",
    "FC Dallas": "fc_dallas",
    "Houston Dynamo FC": "houston_dynamo_fc",
    "Houston Dynamo": "houston_dynamo_fc",
    "Inter Miami CF": "inter_miami_cf",
    "Inter Miami": "inter_miami_cf",
    "LA Galaxy": "la_galaxy",
    "Los Angeles FC": "los_angeles_fc",
    "LAFC": "los_angeles_fc",
    "Minnesota United FC": "minnesota_united_fc",
    "Minnesota United": "minnesota_united_fc",
    "CF Montréal": "cf_montreal",
    "CF Montreal": "cf_montreal",
    "Montreal Impact": "cf_montreal",  # Older name
    "Nashville SC": "nashville_sc",
    "New England Revolution": "new_england_revolution",
    "Revolution": "new_england_revolution",
    "New York City FC": "new_york_city_fc",
    "NYCFC": "new_york_city_fc",
    "New York Red Bulls": "new_york_red_bulls",
    "NY Red Bulls": "new_york_red_bulls",
    "Orlando City SC": "orlando_city_sc",
    "Orlando City": "orlando_city_sc",
    "Philadelphia Union": "philadelphia_union",
    "Union": "philadelphia_union",
    "Portland Timbers": "portland_timbers",
    "Real Salt Lake": "real_salt_lake",
    "RSL": "real_salt_lake",
    "San Jose Earthquakes": "san_jose_earthquakes",
    "Earthquakes": "san_jose_earthquakes",
    "Seattle Sounders FC": "seattle_sounders_fc",
    "Seattle Sounders": "seattle_sounders_fc",
    "Sounders": "seattle_sounders_fc",
    "Sporting Kansas City": "sporting_kansas_city",
    "Sporting KC": "sporting_kansas_city",
    "St. Louis City SC": "st_louis_city_sc",
    "St Louis City SC": "st_louis_city_sc",
    "Toronto FC": "toronto_fc",
    "Vancouver Whitecaps FC": "vancouver_whitecaps_fc",
    "Vancouver Whitecaps": "vancouver_whitecaps_fc",
    "Whitecaps": "vancouver_whitecaps_fc",
}

# EPL Teams (English Premier League)
EPL_TEAM_MAPPINGS = {
    "Arsenal": "arsenal",
    "Arsenal FC": "arsenal",
    "Aston Villa": "aston_villa",
    "Aston Villa FC": "aston_villa",
    "AFC Bournemouth": "afc_bournemouth",
    "Bournemouth": "afc_bournemouth",
    "Brentford": "brentford",
    "Brentford FC": "brentford",
    "Brighton & Hove Albion": "brighton_and_hove_albion",
    "Brighton": "brighton_and_hove_albion",
    "Burnley": "burnley",
    "Burnley FC": "burnley",
    "Chelsea": "chelsea",
    "Chelsea FC": "chelsea",
    "Crystal Palace": "crystal_palace",
    "Crystal Palace FC": "crystal_palace",
    "Everton": "everton",
    "Everton FC": "everton",
    "Fulham": "fulham",
    "Fulham FC": "fulham",
    "Liverpool": "liverpool",
    "Liverpool FC": "liverpool",
    "Luton Town": "luton_town",
    "Luton Town FC": "luton_town",
    "Manchester City": "manchester_city",
    "Man City": "manchester_city",
    "Manchester City FC": "manchester_city",
    "Manchester United": "manchester_united",
    "Man United": "manchester_united",
    "Man Utd": "manchester_united",
    "Manchester United FC": "manchester_united",
    "Newcastle United": "newcastle_united",
    "Newcastle": "newcastle_united",
    "Newcastle United FC": "newcastle_united",
    "Nottingham Forest": "nottingham_forest",
    "Nottm Forest": "nottingham_forest",
    "Nottingham Forest FC": "nottingham_forest",
    "Sheffield United": "sheffield_united",
    "Sheffield Utd": "sheffield_united",
    "Sheffield United FC": "sheffield_united",
    "Tottenham Hotspur": "tottenham_hotspur",
    "Tottenham": "tottenham_hotspur",
    "Spurs": "tottenham_hotspur",
    "Tottenham Hotspur FC": "tottenham_hotspur",
    "West Ham United": "west_ham_united",
    "West Ham": "west_ham_united",
    "West Ham United FC": "west_ham_united",
    "Wolverhampton Wanderers": "wolverhampton_wanderers",
    "Wolves": "wolverhampton_wanderers",
    "Wolverhampton Wanderers FC": "wolverhampton_wanderers",
    # Promoted/relegated teams
    "Leicester City": "leicester_city",
    "Leicester City FC": "leicester_city",
    "Ipswich Town": "ipswich_town",
    "Ipswich Town FC": "ipswich_town",
    "Southampton": "southampton",
    "Southampton FC": "southampton",
}

# La Liga Teams
LA_LIGA_TEAM_MAPPINGS = {
    "Alavés": "alaves",
    "Deportivo Alavés": "alaves",
    "Almería": "almeria",
    "UD Almería": "almeria",
    "Athletic Club": "athletic_club_bilbao",
    "Athletic Bilbao": "athletic_club_bilbao",
    "Atlético Madrid": "atletico_madrid",
    "Atletico Madrid": "atletico_madrid",
    "Barcelona": "fc_barcelona",
    "FC Barcelona": "fc_barcelona",
    "Barça": "fc_barcelona",
    "Real Betis": "real_betis",
    "Cádiz": "cadiz_cf",
    "Cadiz CF": "cadiz_cf",
    "Cádiz CF": "cadiz_cf",
    "Celta Vigo": "celta_vigo",
    "RC Celta de Vigo": "celta_vigo",
    "Getafe": "getafe_cf",
    "Getafe CF": "getafe_cf",
    "Girona": "girona_fc",
    "Girona FC": "girona_fc",
    "Granada": "granada_cf",
    "Granada CF": "granada_cf",
    "Las Palmas": "ud_las_palmas",
    "UD Las Palmas": "ud_las_palmas",
    "Mallorca": "rcd_mallorca",
    "RCD Mallorca": "rcd_mallorca",
    "Osasuna": "ca_osasuna",
    "CA Osasuna": "ca_osasuna",
    "Rayo Vallecano": "rayo_vallecano",
    "Real Madrid": "real_madrid",
    "Real Sociedad": "real_sociedad",
    "Sevilla": "sevilla_fc",
    "Sevilla FC": "sevilla_fc",
    "Valencia": "valencia_cf",
    "Valencia CF": "valencia_cf",
    "Villarreal": "villarreal_cf",
    "Villarreal CF": "villarreal_cf",
    # Promoted teams
    "Leganés": "cd_leganes",
    "CD Leganés": "cd_leganes",
    "Valladolid": "real_valladolid",
    "Real Valladolid": "real_valladolid",
}

# Serie A Teams
SERIE_A_TEAM_MAPPINGS = {
    "Atalanta": "atalanta_bc",
    "Atalanta BC": "atalanta_bc",
    "Bologna": "bologna_fc_1909",
    "Bologna FC 1909": "bologna_fc_1909",
    "Cagliari": "cagliari_calcio",
    "Empoli": "empoli_fc",
    "Empoli FC": "empoli_fc",
    "Fiorentina": "acf_fiorentina",
    "ACF Fiorentina": "acf_fiorentina",
    "Frosinone": "frosinone_calcio",
    "Genoa": "genoa_cfc",
    "Genoa CFC": "genoa_cfc",
    "Inter": "inter_milan",
    "Inter Milan": "inter_milan",
    "Internazionale": "inter_milan",
    "Juventus": "juventus_fc",
    "Juventus FC": "juventus_fc",
    "Lazio": "ss_lazio",
    "SS Lazio": "ss_lazio",
    "Lecce": "us_lecce",
    "US Lecce": "us_lecce",
    "Milan": "ac_milan",
    "AC Milan": "ac_milan",
    "Monza": "ac_monza",
    "AC Monza": "ac_monza",
    "Napoli": "ssc_napoli",
    "SSC Napoli": "ssc_napoli",
    "Roma": "as_roma",
    "AS Roma": "as_roma",
    "Salarnitana": "us_salernitana_1919",
    "Sassuolo": "us_sassuolo_calcio",
    "Torino": "torino_fc",
    "Torino FC": "torino_fc",
    "Udinese": "udinese_calcio",
    "Hellas Verona": "hellas_verona_fc",
    "Verona": "hellas_verona_fc",
    # Promoted teams
    "Parma": "parma_calcio_1913",
    "Como": "como_1907",
    "Venezia": "venezia_fc",
    "Venezia FC": "venezia_fc",
}

# Bundesliga Teams
BUNDESLIGA_TEAM_MAPPINGS = {
    "FC Augsburg": "fc_augsburg",
    "Augsburg": "fc_augsburg",
    "Bayer Leverkusen": "bayer_04_leverkusen",
    "Leverkusen": "bayer_04_leverkusen",
    "Bayern Munich": "fc_bayern_munich",
    "Bayern München": "fc_bayern_munich",
    "FC Bayern": "fc_bayern_munich",
    "VfL Bochum": "vfl_bochum",
    "Bochum": "vfl_bochum",
    "Werder Bremen": "sv_werder_bremen",
    "Bremen": "sv_werder_bremen",
    "Darmstadt 98": "sv_darmstadt_98",
    "Darmstadt": "sv_darmstadt_98",
    "Borussia Dortmund": "borussia_dortmund",
    "Dortmund": "borussia_dortmund",
    "BVB": "borussia_dortmund",
    "Eintracht Frankfurt": "eintracht_frankfurt",
    "Frankfurt": "eintracht_frankfurt",
    "SC Freiburg": "sc_freiburg",
    "Freiburg": "sc_freiburg",
    "Borussia Mönchengladbach": "borussia_monchengladbach",
    "Gladbach": "borussia_monchengladbach",
    "1. FC Heidenheim": "fc_heidenheim",
    "Heidenheim": "fc_heidenheim",
    "TSG Hoffenheim": "tsg_1899_hoffenheim",
    "Hoffenheim": "tsg_1899_hoffenheim",
    "1. FC Köln": "fc_koln",
    "FC Koln": "fc_koln",
    "Köln": "fc_koln",
    "RB Leipzig": "rb_leipzig",
    "Leipzig": "rb_leipzig",
    "Mainz 05": "fsv_mainz_05",
    "1. FSV Mainz 05": "fsv_mainz_05",
    "Mainz": "fsv_mainz_05",
    "VfB Stuttgart": "vfb_stuttgart",
    "Stuttgart": "vfb_stuttgart",
    "Union Berlin": "fc_union_berlin",
    "1. FC Union Berlin": "fc_union_berlin",
    "VfL Wolfsburg": "vfl_wolfsburg",
    "Wolfsburg": "vfl_wolfsburg",
    # Promoted teams
    "FC St. Pauli": "fc_st_pauli",
    "St. Pauli": "fc_st_pauli",
    "Holstein Kiel": "holstein_kiel",
}

# Ligue 1 Teams
LIGUE_1_TEAM_MAPPINGS = {
    "AS Monaco": "as_monaco",
    "Monaco": "as_monaco",
    "Clermont Foot": "clermont_foot_63",
    "Clermont": "clermont_foot_63",
    "Le Havre": "le_havre_ac",
    "RC Lens": "rc_lens",
    "Lens": "rc_lens",
    "Lille OSC": "lille_osc",
    "Lille": "lille_osc",
    "LOSC": "lille_osc",
    "FC Lorient": "fc_lorient",
    "Lorient": "fc_lorient",
    "Olympique Lyonnais": "olympique_lyonnais",
    "Lyon": "olympique_lyonnais",
    "Olympique de Marseille": "olympique_marseille",
    "Marseille": "olympique_marseille",
    "FC Metz": "fc_metz",
    "Metz": "fc_metz",
    "Montpellier HSC": "montpellier_hsc",
    "Montpellier": "montpellier_hsc",
    "FC Nantes": "fc_nantes",
    "Nantes": "fc_nantes",
    "OGC Nice": "ogc_nice",
    "Nice": "ogc_nice",
    "Paris Saint-Germain": "paris_saint_germain",
    "PSG": "paris_saint_germain",
    "Paris SG": "paris_saint_germain",
    "Stade Brestois 29": "stade_brestois_29",
    "Brest": "stade_brestois_29",
    "Stade de Reims": "stade_de_reims",
    "Reims": "stade_de_reims",
    "Stade Rennais FC": "stade_rennais_fc",
    "Rennes": "stade_rennais_fc",
    "Stade Rennais": "stade_rennais_fc",
    "RC Strasbourg Alsace": "rc_strasbourg_alsace",
    "Strasbourg": "rc_strasbourg_alsace",
    "Toulouse FC": "toulouse_fc",
    # Promoted teams
    "AJ Auxerre": "aj_auxerre",
    "Auxerre": "aj_auxerre",
    "Angers SCO": "angers_sco",
    "Angers": "angers_sco",
}
