"""
Prop Type Templates Configuration
Defines available prop types for each league with labels, placeholders, and validation rules.
"""

from dataclasses import dataclass
from typing import Dict, List


@dataclass
class PropTemplate:
    """Template for a specific prop type."""

    label: str
    placeholder: str
    unit: str
    min_value: float = 0.0
    max_value: float = 999.9
    decimal_places: int = 1
    validation_regex: str = r"^\d+(\.\d+)?$"


# Prop type templates for each league
PROP_TEMPLATES: Dict[str, Dict[str, PropTemplate]] = {
    "NBA": {
                 "points": PropTemplate(
             label="Points",
             placeholder="Over/Under X.X Points",
             unit="points",
             min_value=0.0,
             max_value=400.0,
             decimal_places=1,
         ),
        "rebounds": PropTemplate(
            label="Rebounds",
            placeholder="Over/Under X.X Rebounds",
            unit="rebounds",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
        "assists": PropTemplate(
            label="Assists",
            placeholder="Over/Under X.X Assists",
            unit="assists",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "threes": PropTemplate(
            label="3-Pointers Made",
            placeholder="Over/Under X.X 3-Pointers",
            unit="3-pointers",
            min_value=0.0,
            max_value=30.0,
            decimal_places=1,
        ),
        "steals": PropTemplate(
            label="Steals",
            placeholder="Over/Under X.X Steals",
            unit="steals",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "blocks": PropTemplate(
            label="Blocks",
            placeholder="Over/Under X.X Blocks",
            unit="blocks",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "turnovers": PropTemplate(
            label="Turnovers",
            placeholder="Over/Under X.X Turnovers",
            unit="turnovers",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "minutes": PropTemplate(
            label="Minutes Played",
            placeholder="Over/Under X.X Minutes",
            unit="minutes",
            min_value=0.0,
            max_value=96.0,
            decimal_places=1,
        ),
        "field_goals": PropTemplate(
            label="Field Goals Made",
            placeholder="Over/Under X.X FGs",
            unit="field goals",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "field_goal_attempts": PropTemplate(
            label="Field Goal Attempts",
            placeholder="Over/Under X.X FGA",
            unit="attempts",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
        "free_throws": PropTemplate(
            label="Free Throws Made",
            placeholder="Over/Under X.X FTs",
            unit="free throws",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "free_throw_attempts": PropTemplate(
            label="Free Throw Attempts",
            placeholder="Over/Under X.X FTA",
            unit="attempts",
            min_value=0.0,
            max_value=50.0,
            decimal_places=1,
        ),
        "offensive_rebounds": PropTemplate(
            label="Offensive Rebounds",
            placeholder="Over/Under X.X OReb",
            unit="rebounds",
            min_value=0.0,
            max_value=30.0,
            decimal_places=1,
        ),
        "defensive_rebounds": PropTemplate(
            label="Defensive Rebounds",
            placeholder="Over/Under X.X DReb",
            unit="rebounds",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "personal_fouls": PropTemplate(
            label="Personal Fouls",
            placeholder="Over/Under X.X Fouls",
            unit="fouls",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "plus_minus": PropTemplate(
            label="Plus/Minus",
            placeholder="Over/Under X.X +/-",
            unit="points",
            min_value=-50.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "double_double": PropTemplate(
            label="Double Double",
            placeholder="Over/Under X.X DD",
            unit="double doubles",
            min_value=0.0,
            max_value=1.0,
            decimal_places=0,
        ),
        "triple_double": PropTemplate(
            label="Triple Double",
            placeholder="Over/Under X.X TD",
            unit="triple doubles",
            min_value=0.0,
            max_value=1.0,
            decimal_places=0,
        ),
    },
    "NFL": {
        "passing_yards": PropTemplate(
            label="Passing Yards",
            placeholder="Over/Under XXX.X Yards",
            unit="yards",
            min_value=0.0,
            max_value=1200.0,
            decimal_places=1,
        ),
        "rushing_yards": PropTemplate(
            label="Rushing Yards",
            placeholder="Over/Under XX.X Yards",
            unit="yards",
            min_value=0.0,
            max_value=400.0,
            decimal_places=1,
        ),
        "receiving_yards": PropTemplate(
            label="Receiving Yards",
            placeholder="Over/Under XXX.X Yards",
            unit="yards",
            min_value=0.0,
            max_value=600.0,
            decimal_places=1,
        ),
        "receptions": PropTemplate(
            label="Receptions",
            placeholder="Over/Under X.X Receptions",
            unit="receptions",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "touchdowns": PropTemplate(
            label="Touchdowns",
            placeholder="Over/Under X.X TDs",
            unit="touchdowns",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "passing_touchdowns": PropTemplate(
            label="Passing TDs",
            placeholder="Over/Under X.X Passing TDs",
            unit="touchdowns",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "rushing_touchdowns": PropTemplate(
            label="Rushing TDs",
            placeholder="Over/Under X.X Rushing TDs",
            unit="touchdowns",
            min_value=0.0,
            max_value=12.0,
            decimal_places=1,
        ),
        "receiving_touchdowns": PropTemplate(
            label="Receiving TDs",
            placeholder="Over/Under X.X Receiving TDs",
            unit="touchdowns",
            min_value=0.0,
            max_value=12.0,
            decimal_places=1,
        ),
        "interceptions": PropTemplate(
            label="Interceptions",
            placeholder="Over/Under X.X INTs",
            unit="interceptions",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "pass_attempts": PropTemplate(
            label="Pass Attempts",
            placeholder="Over/Under X.X Pass Att",
            unit="attempts",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "pass_completions": PropTemplate(
            label="Pass Completions",
            placeholder="Over/Under X.X Comp",
            unit="completions",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
        "rush_attempts": PropTemplate(
            label="Rush Attempts",
            placeholder="Over/Under X.X Rush Att",
            unit="attempts",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
        "targets": PropTemplate(
            label="Targets",
            placeholder="Over/Under X.X Targets",
            unit="targets",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "fumbles": PropTemplate(
            label="Fumbles",
            placeholder="Over/Under X.X Fumbles",
            unit="fumbles",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "fumbles_lost": PropTemplate(
            label="Fumbles Lost",
            placeholder="Over/Under X.X Fum Lost",
            unit="fumbles",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "sacks": PropTemplate(
            label="Sacks",
            placeholder="Over/Under X.X Sacks",
            unit="sacks",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "sack_yards": PropTemplate(
            label="Sack Yards",
            placeholder="Over/Under X.X Sack Yds",
            unit="yards",
            min_value=0.0,
            max_value=80.0,
            decimal_places=1,
        ),
        "longest_pass": PropTemplate(
            label="Longest Pass",
            placeholder="Over/Under X.X Long Pass",
            unit="yards",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "longest_rush": PropTemplate(
            label="Longest Rush",
            placeholder="Over/Under X.X Long Rush",
            unit="yards",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "longest_reception": PropTemplate(
            label="Longest Reception",
            placeholder="Over/Under X.X Long Rec",
            unit="yards",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "passer_rating": PropTemplate(
            label="Passer Rating",
            placeholder="Over/Under X.X Rating",
            unit="rating",
            min_value=0.0,
            max_value=175.0,
            decimal_places=1,
        ),
        "completion_percentage": PropTemplate(
            label="Completion %",
            placeholder="Over/Under X.X Comp %",
            unit="percentage",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "yards_per_attempt": PropTemplate(
            label="Yards Per Attempt",
            placeholder="Over/Under X.X YPA",
            unit="yards",
            min_value=0.0,
            max_value=30.0,
            decimal_places=1,
        ),
        "yards_per_carry": PropTemplate(
            label="Yards Per Carry",
            placeholder="Over/Under X.X YPC",
            unit="yards",
            min_value=0.0,
            max_value=30.0,
            decimal_places=1,
        ),
        "yards_per_reception": PropTemplate(
            label="Yards Per Reception",
            placeholder="Over/Under X.X YPR",
            unit="yards",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
    },
    "MLB": {
        "hits": PropTemplate(
            label="Hits",
            placeholder="Over/Under X.X Hits",
            unit="hits",
            min_value=0.0,
            max_value=8.0,
            decimal_places=1,
        ),
        "home_runs": PropTemplate(
            label="Home Runs",
            placeholder="Over/Under X.X Home Runs",
            unit="home runs",
            min_value=0.0,
            max_value=8.0,
            decimal_places=1,
        ),
        "rbis": PropTemplate(
            label="RBIs",
            placeholder="Over/Under X.X RBIs",
            unit="RBIs",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "runs": PropTemplate(
            label="Runs",
            placeholder="Over/Under X.X Runs",
            unit="runs",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "strikeouts": PropTemplate(
            label="Strikeouts",
            placeholder="Over/Under X.X Strikeouts",
            unit="strikeouts",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "walks": PropTemplate(
            label="Walks",
            placeholder="Over/Under X.X Walks",
            unit="walks",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "innings_pitched": PropTemplate(
            label="Innings Pitched",
            placeholder="Over/Under X.X Innings",
            unit="innings",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "at_bats": PropTemplate(
            label="At Bats",
            placeholder="Over/Under X.X AB",
            unit="at bats",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "plate_appearances": PropTemplate(
            label="Plate Appearances",
            placeholder="Over/Under X.X PA",
            unit="plate appearances",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "singles": PropTemplate(
            label="Singles",
            placeholder="Over/Under X.X Singles",
            unit="singles",
            min_value=0.0,
            max_value=8.0,
            decimal_places=1,
        ),
        "doubles": PropTemplate(
            label="Doubles",
            placeholder="Over/Under X.X Doubles",
            unit="doubles",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "triples": PropTemplate(
            label="Triples",
            placeholder="Over/Under X.X Triples",
            unit="triples",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "total_bases": PropTemplate(
            label="Total Bases",
            placeholder="Over/Under X.X TB",
            unit="bases",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "stolen_bases": PropTemplate(
            label="Stolen Bases",
            placeholder="Over/Under X.X SB",
            unit="stolen bases",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "caught_stealing": PropTemplate(
            label="Caught Stealing",
            placeholder="Over/Under X.X CS",
            unit="caught stealing",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "sacrifice_flies": PropTemplate(
            label="Sacrifice Flies",
            placeholder="Over/Under X.X SF",
            unit="sacrifice flies",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "sacrifice_bunts": PropTemplate(
            label="Sacrifice Bunts",
            placeholder="Over/Under X.X SAC",
            unit="sacrifice bunts",
            min_value=0.0,
            max_value=2.0,
            decimal_places=1,
        ),
        "ground_into_double_plays": PropTemplate(
            label="GIDP",
            placeholder="Over/Under X.X GIDP",
            unit="GIDP",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "hit_by_pitch": PropTemplate(
            label="Hit By Pitch",
            placeholder="Over/Under X.X HBP",
            unit="HBP",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "batting_average": PropTemplate(
            label="Batting Average",
            placeholder="Over/Under X.XXX AVG",
            unit="average",
            min_value=0.0,
            max_value=1.0,
            decimal_places=3,
        ),
        "on_base_percentage": PropTemplate(
            label="On Base %",
            placeholder="Over/Under X.XXX OBP",
            unit="percentage",
            min_value=0.0,
            max_value=1.0,
            decimal_places=3,
        ),
        "slugging_percentage": PropTemplate(
            label="Slugging %",
            placeholder="Over/Under X.XXX SLG",
            unit="percentage",
            min_value=0.0,
            max_value=6.0,
            decimal_places=3,
        ),
        "ops": PropTemplate(
            label="OPS",
            placeholder="Over/Under X.XXX OPS",
            unit="OPS",
            min_value=0.0,
            max_value=8.0,
            decimal_places=3,
        ),
        "home_run_rate": PropTemplate(
            label="HRR",
            placeholder="Over/Under X.XXX HRR",
            unit="HRR",
            min_value=0.0,
            max_value=2.0,
            decimal_places=3,
        ),
        "wins": PropTemplate(
            label="Wins",
            placeholder="Over/Under X.X Wins",
            unit="wins",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "losses": PropTemplate(
            label="Losses",
            placeholder="Over/Under X.X Losses",
            unit="losses",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "earned_runs": PropTemplate(
            label="Earned Runs",
            placeholder="Over/Under X.X ER",
            unit="earned runs",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "hits_allowed": PropTemplate(
            label="Hits Allowed",
            placeholder="Over/Under X.X HA",
            unit="hits",
            min_value=0.0,
            max_value=24.0,
            decimal_places=1,
        ),
        "walks_allowed": PropTemplate(
            label="Walks Allowed",
            placeholder="Over/Under X.X BB",
            unit="walks",
            min_value=0.0,
            max_value=12.0,
            decimal_places=1,
        ),
        "hit_batters": PropTemplate(
            label="Hit Batters",
            placeholder="Over/Under X.X HB",
            unit="hit batters",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "wild_pitches": PropTemplate(
            label="Wild Pitches",
            placeholder="Over/Under X.X WP",
            unit="wild pitches",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "balks": PropTemplate(
            label="Balks",
            placeholder="Over/Under X.X Balks",
            unit="balks",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "era": PropTemplate(
            label="ERA",
            placeholder="Over/Under X.XX ERA",
            unit="ERA",
            min_value=0.0,
            max_value=40.0,
            decimal_places=2,
        ),
        "whip": PropTemplate(
            label="WHIP",
            placeholder="Over/Under X.XX WHIP",
            unit="WHIP",
            min_value=0.0,
            max_value=10.0,
            decimal_places=2,
        ),
        "strikeouts_per_nine": PropTemplate(
            label="K/9",
            placeholder="Over/Under X.X K/9",
            unit="K/9",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "walks_per_nine": PropTemplate(
            label="BB/9",
            placeholder="Over/Under X.X BB/9",
            unit="BB/9",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "hits_per_nine": PropTemplate(
            label="H/9",
            placeholder="Over/Under X.X H/9",
            unit="H/9",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "home_runs_per_nine": PropTemplate(
            label="HR/9",
            placeholder="Over/Under X.X HR/9",
            unit="HR/9",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "pitches_thrown": PropTemplate(
            label="Pitches Thrown",
            placeholder="Over/Under X.X Pitches",
            unit="pitches",
            min_value=0.0,
            max_value=240.0,
            decimal_places=1,
        ),
        "strikes_thrown": PropTemplate(
            label="Strikes Thrown",
            placeholder="Over/Under X.X Strikes",
            unit="strikes",
            min_value=0.0,
            max_value=200.0,
            decimal_places=1,
        ),
        "balls_thrown": PropTemplate(
            label="Balls Thrown",
            placeholder="Over/Under X.X Balls",
            unit="balls",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "strike_percentage": PropTemplate(
            label="Strike %",
            placeholder="Over/Under X.X Strike %",
            unit="percentage",
            min_value=0.0,
            max_value=200.0,
            decimal_places=1,
        ),
        "quality_starts": PropTemplate(
            label="Quality Starts",
            placeholder="Over/Under X.X QS",
            unit="quality starts",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "complete_games": PropTemplate(
            label="Complete Games",
            placeholder="Over/Under X.X CG",
            unit="complete games",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "shutouts": PropTemplate(
            label="Shutouts",
            placeholder="Over/Under X.X SHO",
            unit="shutouts",
            min_value=0.0,
                max_value=2.0,
            decimal_places=0,
        ),
        "saves": PropTemplate(
            label="Saves",
            placeholder="Over/Under X.X Saves",
            unit="saves",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "holds": PropTemplate(
            label="Holds",
            placeholder="Over/Under X.X Holds",
            unit="holds",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "blown_saves": PropTemplate(
            label="Blown Saves",
            placeholder="Over/Under X.X BS",
            unit="blown saves",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
    },
    "NHL": {
        "goals": PropTemplate(
            label="Goals",
            placeholder="Over/Under X.X Goals",
            unit="goals",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "assists": PropTemplate(
            label="Assists",
            placeholder="Over/Under X.X Assists",
            unit="assists",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "points": PropTemplate(
            label="Points",
            placeholder="Over/Under X.X Points",
            unit="points",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "shots": PropTemplate(
            label="Shots on Goal",
            placeholder="Over/Under X.X Shots",
            unit="shots",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "saves": PropTemplate(
            label="Saves",
            placeholder="Over/Under X.X Saves",
            unit="saves",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "penalty_minutes": PropTemplate(
            label="Penalty Minutes",
            placeholder="Over/Under X.X PIM",
            unit="minutes",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "power_play_goals": PropTemplate(
            label="Power Play Goals",
            placeholder="Over/Under X.X PPG",
            unit="goals",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "power_play_assists": PropTemplate(
            label="Power Play Assists",
            placeholder="Over/Under X.X PPA",
            unit="assists",
            min_value=0.0,
                    max_value=6.0,
            decimal_places=1,
        ),
        "power_play_points": PropTemplate(
            label="Power Play Points",
            placeholder="Over/Under X.X PPP",
            unit="points",
            min_value=0.0,
            max_value=8.0,
            decimal_places=1,
        ),
        "short_handed_goals": PropTemplate(
            label="Short Handed Goals",
            placeholder="Over/Under X.X SHG",
            unit="goals",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "short_handed_assists": PropTemplate(
            label="Short Handed Assists",
            placeholder="Over/Under X.X SHA",
            unit="assists",
            min_value=0.0,
            max_value=4.0,
            decimal_places=1,
        ),
        "short_handed_points": PropTemplate(
            label="Short Handed Points",
            placeholder="Over/Under X.X SHP",
            unit="points",
            min_value=0.0,
            max_value=6.0,
            decimal_places=1,
        ),
        "game_winning_goals": PropTemplate(
            label="Game Winning Goals",
            placeholder="Over/Under X.X GWG",
            unit="goals",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "overtime_goals": PropTemplate(
            label="Overtime Goals",
            placeholder="Over/Under X.X OTG",
            unit="goals",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "empty_net_goals": PropTemplate(
            label="Empty Net Goals",
            placeholder="Over/Under X.X ENG",
            unit="goals",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "hits": PropTemplate(
            label="Hits",
            placeholder="Over/Under X.X Hits",
            unit="hits",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "blocks": PropTemplate(
            label="Blocks",
            placeholder="Over/Under X.X Blocks",
            unit="blocks",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "faceoffs_won": PropTemplate(
            label="Faceoffs Won",
            placeholder="Over/Under X.X FO Won",
            unit="faceoffs",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "faceoffs_lost": PropTemplate(
            label="Faceoffs Lost",
            placeholder="Over/Under X.X FO Lost",
            unit="faceoffs",
            min_value=0.0,
            max_value=40.0,
            decimal_places=1,
        ),
        "faceoff_percentage": PropTemplate(
            label="Faceoff %",
            placeholder="Over/Under X.X FO %",
            unit="percentage",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "giveaways": PropTemplate(
            label="Giveaways",
            placeholder="Over/Under X.X Giveaways",
            unit="giveaways",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "takeaways": PropTemplate(
            label="Takeaways",
            placeholder="Over/Under X.X Takeaways",
            unit="takeaways",
            min_value=0.0,
            max_value=10.0,
            decimal_places=1,
        ),
        "plus_minus": PropTemplate(
            label="Plus/Minus",
            placeholder="Over/Under X.X +/-",
            unit="plus/minus",
            min_value=-5.0,
            max_value=5.0,
            decimal_places=1,
        ),
        "time_on_ice": PropTemplate(
            label="Time on Ice",
            placeholder="Over/Under X.X TOI",
            unit="minutes",
            min_value=0.0,
            max_value=60.0,
            decimal_places=1,
        ),
        "power_play_time": PropTemplate(
            label="Power Play Time",
            placeholder="Over/Under X.X PP TOI",
            unit="minutes",
            min_value=0.0,
            max_value=20.0,
            decimal_places=1,
        ),
        "short_handed_time": PropTemplate(
            label="Short Handed Time",
            placeholder="Over/Under X.X SH TOI",
            unit="minutes",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "even_strength_time": PropTemplate(
            label="Even Strength Time",
            placeholder="Over/Under X.X ES TOI",
            unit="minutes",
            min_value=0.0,
            max_value=50.0,
            decimal_places=1,
        ),
        "goals_against": PropTemplate(
            label="Goals Against",
            placeholder="Over/Under X.X GA",
            unit="goals",
            min_value=0.0,
            max_value=16.0,
            decimal_places=1,
        ),
        "shots_against": PropTemplate(
            label="Shots Against",
            placeholder="Over/Under X.X SA",
            unit="shots",
            min_value=0.0,
            max_value=100.0,
            decimal_places=1,
        ),
        "save_percentage": PropTemplate(
            label="Save %",
            placeholder="Over/Under X.XXX SV%",
            unit="percentage",
            min_value=0.0,
            max_value=2.0,
            decimal_places=3,
        ),
        "goals_against_average": PropTemplate(
            label="GAA",
            placeholder="Over/Under X.XX GAA",
            unit="GAA",
            min_value=0.0,
            max_value=20.0,
            decimal_places=2,
        ),
        "shutouts": PropTemplate(
            label="Shutouts",
            placeholder="Over/Under X.X SO",
            unit="shutouts",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "wins": PropTemplate(
            label="Wins",
            placeholder="Over/Under X.X Wins",
            unit="wins",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "losses": PropTemplate(
            label="Losses",
            placeholder="Over/Under X.X Losses",
            unit="losses",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
        "overtime_losses": PropTemplate(
            label="Overtime Losses",
            placeholder="Over/Under X.X OTL",
            unit="overtime losses",
            min_value=0.0,
            max_value=2.0,
            decimal_places=0,
        ),
    },
}

# League-specific prop type groupings
LEAGUE_PROP_GROUPS: Dict[str, Dict[str, List[str]]] = {
    "NBA": {
        "Scoring": ["points", "threes", "field_goals", "free_throws", "plus_minus"],
        "Rebounding": ["rebounds", "offensive_rebounds", "defensive_rebounds"],
        "Playmaking": ["assists", "turnovers"],
        "Defense": ["steals", "blocks"],
        "Playing Time": ["minutes"],
        "Advanced": ["double_double", "triple_double", "personal_fouls"],
        "Shooting": ["field_goal_attempts", "free_throw_attempts"],
    },
    "NFL": {
        "Passing": [
            "passing_yards",
            "passing_touchdowns",
            "interceptions",
            "pass_attempts",
            "pass_completions",
            "passer_rating",
            "completion_percentage",
            "yards_per_attempt",
            "longest_pass",
        ],
        "Rushing": [
            "rushing_yards",
            "rushing_touchdowns",
            "rush_attempts",
            "yards_per_carry",
            "longest_rush",
        ],
        "Receiving": [
            "receiving_yards",
            "receptions",
            "receiving_touchdowns",
            "targets",
            "yards_per_reception",
            "longest_reception",
        ],
        "Scoring": ["touchdowns"],
        "Defense": ["sacks", "sack_yards", "fumbles", "fumbles_lost"],
    },
    "MLB": {
        "Batting": [
            "hits",
            "home_runs",
            "rbis",
            "runs",
            "walks",
            "at_bats",
            "plate_appearances",
            "singles",
            "doubles",
            "triples",
            "total_bases",
            "stolen_bases",
            "caught_stealing",
            "batting_average",
            "on_base_percentage",
            "slugging_percentage",
            "ops",
            "hits_runs_rbis",
        ],
        "Pitching": [
            "strikeouts",
            "innings_pitched",
            "earned_runs",
            "hits_allowed",
            "walks_allowed",
            "hit_batters",
            "wild_pitches",
            "balks",
            "era",
            "whip",
            "strikeouts_per_nine",
            "walks_per_nine",
            "hits_per_nine",
            "home_runs_per_nine",
            "pitches_thrown",
            "strikes_thrown",
            "balls_thrown",
            "strike_percentage",
        ],
        "Advanced": [
            "sacrifice_flies",
            "sacrifice_bunts",
            "ground_into_double_plays",
            "hit_by_pitch",
        ],
        "Outcomes": [
            "wins",
            "losses",
            "quality_starts",
            "complete_games",
            "shutouts",
            "saves",
            "holds",
            "blown_saves",
        ],
    },
    "NHL": {
        "Scoring": [
            "goals",
            "assists",
            "points",
            "power_play_goals",
            "power_play_assists",
            "power_play_points",
            "short_handed_goals",
            "short_handed_assists",
            "short_handed_points",
            "game_winning_goals",
            "overtime_goals",
            "empty_net_goals",
        ],
        "Shooting": ["shots"],
        "Goaltending": [
            "saves",
            "goals_against",
            "shots_against",
            "save_percentage",
            "goals_against_average",
            "shutouts",
        ],
        "Physical": ["hits", "blocks", "penalty_minutes"],
        "Faceoffs": ["faceoffs_won", "faceoffs_lost", "faceoff_percentage"],
        "Possession": ["giveaways", "takeaways", "plus_minus"],
        "Time on Ice": [
            "time_on_ice",
            "power_play_time",
            "short_handed_time",
            "even_strength_time",
        ],
        "Outcomes": ["wins", "losses", "overtime_losses"],
    },
}


def get_prop_templates_for_league(league: str) -> Dict[str, PropTemplate]:
    """Get prop templates for a specific league."""
    return PROP_TEMPLATES.get(league.upper(), {})


def get_prop_groups_for_league(league: str) -> Dict[str, List[str]]:
    """Get prop type groups for a specific league."""
    return LEAGUE_PROP_GROUPS.get(league.upper(), {})


def validate_prop_value(league: str, prop_type: str, value: float) -> bool:
    """Validate a prop value against the template constraints."""
    templates = get_prop_templates_for_league(league)
    if prop_type not in templates:
        return False

    template = templates[prop_type]
    return template.min_value <= value <= template.max_value


def format_prop_line(league: str, prop_type: str, value: float) -> str:
    """Format a prop line value according to the template."""
    templates = get_prop_templates_for_league(league)
    if prop_type not in templates:
        return str(value)

    template = templates[prop_type]
    return f"{value:.{template.decimal_places}f} {template.unit}"
