# General Bot Settings
betting:
  min_units: 1
  max_units: 3
  default_units: 1

# Database Configuration
database:
  db_path: data/betting.db
  cache_dir: data/cache

# Logging Configuration
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/betting_bot.log

# API Configuration
api:
  timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 5  # seconds
  # api_key: Use .env or secret manager for sensitive data

# Cache Configuration
cache:
  ttl: 3600  # 1 hour in seconds
  max_size: 1000
  game_ttl: 300
  league_ttl: 86400
  team_ttl: 86400
  user_ttl: 86400

# Betting Rules
betting_rules:
  min_odds: -1000
  max_odds: 1000
  allowed_bet_types:
    - moneyline
    - spread
    - total
  allowed_leagues:
    - NBA
    - NFL
    - MLB
    - NHL
    - MLS
    - Brazil Serie A
    - Other

# Voice Channel Configuration
voice_channel:
  check_interval: 300  # 5 minutes
  grace_period: 3600   # 1 hour

# Analytics Configuration
analytics:
  update_interval: 3600  # 1 hour
  retention_days: 30
